#!/bin/bash
cd $OPENSHIFT_DATA_DIR

# Download Maven if not already installed
if [ ! -d apache-maven-3.3.3 ]; then
  wget http://www.eu.apache.org/dist/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz
  tar -zxf apache-maven-3.3.3-bin.tar.gz
fi

# Download Java8 if not already installed
if [ ! -d jdk1.8.0_65 ]; then
  wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u65-b16/jdk-8u65-linux-i586.tar.gz
  tar -zxf jdk-8u65-linux-i586.tar.gz
fi
